providers = ["node"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm install --production=false"

[phases.build]
dependsOn = ["install"]
cmd = "npm run build"

[start]
cmd = "serve -s dist -l 3000"

# Explicitly override any auto-detected commands
[build]
cmd = "npm run build"
